### ISSUE TITLE
 msg = near "from": syntax error

### ISSUE THREAD

**Issue by roytan883** [litesuits/android-lite-orm#1]
如果我的对象中一个字段名叫from，liteorm直接就报错了。log显示create table就失败了。 msg = near "from": syntax error 这样的字段话取名还要想想想是不是和sql命令冲突？
我测试加这句就好了@Column("ffrom")，但这样好难用。。。

   @PrimaryKey(PrimaryKey.AssignType.BY_MYSELF)
    @Column("id")
    private String id;
    private String textContent;
    private String from;
    private String to;

**Comment by johnwatson5412** [comment]
笑死我了，支持@roytan883，哈哈哈。醉了。

**Comment by johnwatson5412** [comment]
话说，作者也不赖维护。。。

**Comment by litesuits** [comment]
卧槽，我来晚了。。
请注意：
1. SQL语句里绝对不能有关键词from select where等等，就像java中不能有命名变量为int，byte一样。这无需多言。
2. 如果你不写@Column("")注解，默认反射用变量名字做数据表列名。
3. 根据1，列名不能有关键字，请注意避免。

别逗我了，这库不奇葩。

**Comment by roytan883** [comment]
1. SQL语句里绝对不能有关键词from select where等等，就像java中不能有命名变量为int，byte一样。这无需多言。????????????????? 你确信。????????????????? 

SQL中用单引号转义都不懂？需要给你贴个教程不？这作者也是奇葩！！！

**Comment by roytan883** [comment]
3，需要我贴段代码SQL定义列名为关键字的不？

**Comment by litesuits** [comment]
我也是醉了

**Comment by litesuits** [comment]
SQL语法的建议是尽量不要使用关键字。建议开发者自己在关键字列名前加个下划线，不干扰可读性，也避免潜在问题，框架给加括号或引号要穷举关键字也降低效率

**Comment by roytan883** [comment]
1，'SQL语句里绝对不能有关键词', 不知道是我理解错了，还是我没看懂，但最后结果是SQL里面可以有关键字是吧？是不是打你脸了？
2，好你现在说要尽量避免，那我是不是这样理解：简单的说，就是别人家的SQL orm可以定义任意字段名，你家的强行背单词是吧？from to 这些超常用的通信系统结构字段名到你家就玩不转了是吧？
3，这话题没意义了，一个连正视自己技术上错误的勇气都没有repo作者，没有必要再讨论了。

**Comment by litesuits** [comment]
难道SQL语句中可以有关键词？当然要处理！你牛逼你写个好了，你技术屌你来写个更牛逼的不就解决了，别在这叨叨了

**Comment by litesuits** [comment]
或者为开源项目推送修复、完善功能不也挺好吗。好好说话不行？非得语言攻击，撕逼啊，很爽是吧，有病

**Comment by litesuits** [comment]
之前的说法确实有问题，现在情况就是框架针对SQL语句中关键字确实没有做处理，所以不能有，只能开发者自己避免。后边想好了，再完善一下

**Comment by roytan883** [comment]
我能这么有底气的撕逼，是因为我在很早前和那人喷之前都敲了代码改库测试通过了，证明是可以处理字段名为SQL关键字的情况下才发的。
本以为我都已经写得很明白了，包括怎么用单引号转义都说了，但是没有想到你作为作者来居然都不先好好看问题，都还没有实际测试，上来就信口开河和那人一样号称什么绝对不能有关键字同名字段。
其实处理起来很简单，就是生成SQL语句的时候，在字段名那个地方用单引号包一下，修改几行代码而已的事情。我反感的是都不先技术验证就来撕逼，很无聊。

**Comment by litesuits** [comment]
是的，是需要加中括号或者引号来‘转义’。
如果每个字段都加引号也不妥，所以最好是判断列名是不是关键字，穷举关键字后需要对关键字字段做‘转义’，也似乎影响性能。
我再想想，后边抽空给解决一下

**Comment by zouzhenglu** [comment]
全部都加上为什么不行，那你让人故意在名字上加上那个引号的咋办
