### ISSUE TITLE
子元素是List集合，能保存关联。却无法取出。

### ISSUE THREAD

**Issue by sfyc23** [litesuits/android-lite-orm#11]
package com.litesuits.orm.junit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.litesuits.orm.LiteOrm;
import com.litesuits.orm.db.annotation.Column;
import com.litesuits.orm.db.annotation.Mapping;
import com.litesuits.orm.db.annotation.PrimaryKey;
import com.litesuits.orm.db.annotation.Table;
import com.litesuits.orm.db.enums.AssignType;
import com.litesuits.orm.db.enums.Relation;
import com.litesuits.orm.model.demo.Teacher;

import android.content.Context;
import android.os.Environment;
import android.test.AndroidTestCase;

public class MyDemoTest extends AndroidTestCase {
	
	public static final String DB_NAME = Environment
			.getExternalStorageDirectory().getAbsolutePath()
			+ "/lite/orm/love.db";
	
	public void estHello() {
		System.out.println("你好");
	}
	
	public void estSaveData() {
	    Context mContext = getContext();
	    LiteOrm liteOrm = LiteOrm.newCascadeInstance(mContext, DB_NAME);
	    liteOrm.save(new Teacher("丽华", 23));
		liteOrm.save(getHomeTypeList());
		
	}
	
	public void estDeleteData(){
		Context mContext = getContext();
	    LiteOrm liteOrm = LiteOrm.newCascadeInstance(mContext, DB_NAME);
		liteOrm.delete(HomeType.class);
	}
	
	public void testGetData(){
		Context mContext = getContext();
	    LiteOrm liteOrm = LiteOrm.newCascadeInstance(mContext, DB_NAME);
	    List<HomeType> hy = liteOrm.query(HomeType.class);
	    System.out.println("hy = "+hy.toString());
		
	}
	
	public List<HomeType> getHomeTypeList(){
		List<HomeType>  homeTypes = new ArrayList<MyDemoTest.HomeType>();
		
		for (int i = 1; i <= 3; i++) {
			List<UserHome> userhomes = new ArrayList<MyDemoTest.UserHome>();
			UserHome[] uhs = new UserHome[3];
			for (int j = 1; j <= 3; j++) {
				userhomes.add(new UserHome("uid" + i + j, "nickname" + i + j));
				uhs[j-1] = new UserHome("uid" + i + j, "nickname" + i + j);
			}
//			homeTypes.add(new HomeType("hometypelist:" + i, "title," + i,
//					(UserHome[]) (userhomes.toArray())));
//			homeTypes.add(new HomeType("hometypelist:" + i, "title," + i,
//					uhs));
			homeTypes.add(new HomeType("hometypelist:" + i, "title," + i,
					userhomes));
		}
		return homeTypes; 
	}
	

	@Table("home_type")
	public static class HomeType implements Serializable {

		private static final long serialVersionUID = -6048223356798388872L;
		public static final String VISIBLE = "1";
		public static final String NONE = "0";

		@PrimaryKey(AssignType.AUTO_INCREMENT)
		@Column("db_id")
		private long db_id;
		
		@Column("hometypelist")
		private String hometypelist;
		@Column("type_id")
		private String type_id;
		private String title;
		private String image;
		private String typeinfo;
		private String home_image;

		/** 推荐是否有更多 0无 1 有 */
		private String usermore;
		
		@Mapping(Relation.OneToMany)
		@Column("userlist")
//		private UserHome[] userlist;
		private List<UserHome> userList;

		private HomeType(String hometypelist, String title,
				List<UserHome> userList) {
			this.hometypelist = hometypelist;
			this.title = title;
			this.userList = userList;
		}
		

		public String getHometypelist() {
			return hometypelist;
		}

		public void setHometypelist(String hometypelist) {
			this.hometypelist = hometypelist;
		}

		public String getType_id() {
			return type_id;
		}

		public void setType_id(String type_id) {
			this.type_id = type_id;
		}

		public String getTitle() {
			return title;
		}

		public void setTitle(String title) {
			this.title = title;
		}

		public String getImage() {
			return image;
		}

		public void setImage(String image) {
			this.image = image;
		}

		public String getTypeinfo() {
			return typeinfo;
		}

		public void setTypeinfo(String typeinfo) {
			this.typeinfo = typeinfo;
		}

//		public UserHome[] getUserlist() {
//			return userlist;
//		}
//
//		public void setUserlist(UserHome[] userlist) {
//			this.userlist = userlist;
//		}

		public String getHome_image() {
			return home_image;
		}

		public void setHome_image(String home_image) {
			this.home_image = home_image;
		}

		/** 推荐是否有更多 0无 1 有 */
		public String getUsermore() {
			return usermore;
		}

		public void setUsermore(String usermore) {
			this.usermore = usermore;
		}

		@Override
		public String toString() {
			return "HomeType [hometypelist=" + hometypelist + ", type_id="
					+ type_id + ", title=" + title + ", image=" + image
					+ ", typeinfo=" + typeinfo + ", home_image=" + home_image
//					+ ", userlist=" + Arrays.toString(userlist) + "]";
					+ ", userlist=" + userList.toString() + "]";
		}

	}

	@Table("user_home")
	public static class UserHome implements Serializable {

		private static final long serialVersionUID = -1311542533996146739L;

		@PrimaryKey(AssignType.AUTO_INCREMENT)
		@Column("db_id")
		private long db_id;
		
		@Column("uid")
		private String uid;
		@Column("easemob_uuid")
		private String easemob_uuid;
		@Column("gender")
		private String gender;
		@Column("nickname")
		private String nickname;
		@Column("header")
		private String header;
		@Column("voice")
		private String voice;
		@Column("voice_time")
		private String voice_time;
		
		

		private UserHome(String uid, String nickname) {
			this.uid = uid;
			this.nickname = nickname;
		}

		public String getUid() {
			return uid;
		}

		public void setUid(String uid) {
			this.uid = uid;
		}

		public String getEasemob_uuid() {
			return easemob_uuid;
		}

		public void setEasemob_uuid(String easemob_uuid) {
			this.easemob_uuid = easemob_uuid;
		}

		public String getGender() {
			return gender;
		}

		public void setGender(String gender) {
			this.gender = gender;
		}

		public String getNickname() {
			return nickname;
		}

		public void setNickname(String nickname) {
			this.nickname = nickname;
		}

		public String getHeader() {
			return header;
		}

		public void setHeader(String header) {
			this.header = header;
		}

		public String getVoice() {
			return voice;
		}

		public void setVoice(String voice) {
			this.voice = voice;
		}

		public String getVoice_time() {
			return voice_time;
		}

		public void setVoice_time(String voice_time) {
			this.voice_time = voice_time;
		}

		@Override
		public String toString() {
			return "UserHome [db_id=" + db_id + ", uid=" + uid
					+ ", easemob_uuid=" + easemob_uuid + ", gender=" + gender
					+ ", nickname=" + nickname + ", header=" + header
					+ ", voice=" + voice + ", voice_time=" + voice_time + "]";
		}
		
	}
}

**Comment by litesuits** [comment]
已修复查询问题，使用v1.7.0 新版本~
