### ISSUE TITLE
LiteOrm.newSingleInstance(Context context, String dbName) 初始化后紧接着调用查询会查询不到内容

### ISSUE THREAD

**Issue by drakeet** [litesuits/android-lite-orm#14]
版本：1.6.0、1.6.3
使用 `LiteOrm.newSingleInstance(Context context, String dbName)` 初始化数据库之后，紧接着调用`query` 查询会查询不到内容，即使数据库中其实有结果数据。除非在查询之前随便 `liteOrm.save(...)` 一下，QAQ 被坑了一整个晚上！最后的这个解决方法的发现也是突发奇想...

作者看看是什么原因，修正一下吧😂

**Comment by litesuits** [comment]
已修复，v1.7.0
