### ISSUE TITLE
为什么查询出来的结果主键没有值

### ISSUE THREAD

**Issue by thinkfeed** [litesuits/android-lite-orm#25]
我设置的type为AssignType.BY_MYSELF

**Comment by litesuits** [comment]
AssignType.BY_MYSELF 是指 你需要自己为主键赋值。
AssignType.AUTOINCREMENT 是框架为其赋值，自增主键。
烦请确认后关闭issue~

**Comment by thinkfeed** [comment]
谢谢 回复，但是我AssignType.AUTOINCREMENT查出来的数据主键值都是0，Cascade模式和signle模式都一样，Cascade模式数据删不掉

**Comment by thinkfeed** [comment]
我的环境是AS 2.0，查询出来的结果主键都不会有值，这是什么原因呢

**Comment by thinkfeed** [comment]
主键不加入属性Map，我找到了这段注释，问题已经知道了
