### ISSUE TITLE
自增id无法返回值

### ISSUE THREAD

**Issue by jinyb09017** [litesuits/android-lite-orm#27]
发现自增加id的值返回都是0
另外boolean的列设置 @Default("true")不能成功

**Comment by thinkfeed** [comment]
我也遇到这个问题

**Comment by litesuits** [comment]
抱歉。、在用 LiteOrm1.9.0 版本的同学，抱歉这个版本由于提升性能，不小心引发了一个bug，是得id不能被查询到。1.9.1已经发布，请更新。
https://github.com/litesuits/android-lite-orm/tree/master/jars
