### ISSUE TITLE
无法更新数据失败

### ISSUE THREAD

**Issue by Ludejin** [litesuits/android-lite-orm#28]
mUserInfo.setIsCurrUser("0");
Log.i("主键",mUserInfo.getId() + "");
ColumnsValue cv = new ColumnsValue(new String[]{"is_curr"});
mLiteOrm.update(mUserInfo, cv, ConflictAlgorithm.None);

这里mUserInfo所有数据正常，主键也存在
![image](https://cloud.githubusercontent.com/assets/10751355/15108073/73cdbe92-1606-11e6-9088-d15c0a83f735.png)

where条件的主键一直是空

**Comment by ervinsae** [comment]
这个怎么解决的 只要是级联的表 update的就有问题
