### ISSUE TITLE
Auto increase ( auto ordered ) with the AssignType.BY_MYSELF

### ISSUE THREAD

**Issue by Sinyuk7** [litesuits/android-lite-orm#36]
在定义主键的时候发现了一个问题:

就是虽然我用了`@PrimaryKey(AssignType.BY_MYSELF)`来注解我数据的xxxId

> xxxId是无规律的整数

但是在保存之后orm会自动根据这个xxxId排序.....好奇怪😶

谁能帮我解答一下...不甚感激O(∩_∩)

**Comment by litesuits** [comment]
这个是主键，主键本身就是索引。会排序
