### ISSUE TITLE
请问可以使用 query 方法进行多表查询吗

### ISSUE THREAD

**Issue by twiceyuan** [litesuits/android-lite-orm#6]
在 sample 看到了查询之后 mapping 的方法，可以将 model 中注解 Relation 的对象映射到一起，请问有没有方法在查询中就做到这个事情？

**Comment by litesuits** [comment]
有。用新版本的cascade实例，可以帮开发者维护关系

**Comment by twiceyuan** [comment]
原来如此，感谢，这个库很好用
